// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `engine`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Engine`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`

/// Pipeline con inferencia mockeada: verifica el cableado sin modelo.
Future<ProposalDto> proposeMocked(
        {required String query, required String fechaHoy}) =>
    RustLib.instance.api
        .crateApiProposeMocked(query: query, fechaHoy: fechaHoy);

/// Pipeline con el engine real. `cact_path` = asset desempaquetado en device.
Future<ProposalDto> proposeReal(
        {required String query,
        required String fechaHoy,
        required String cactPath}) =>
    RustLib.instance.api.crateApiProposeReal(
        query: query, fechaHoy: fechaHoy, cactPath: cactPath);

/// Inicializa la base de datos con clave SQLCipher opcional (hex crudo).
Future<bool> initDatabase({required String dbPath, String? rawKeyHex}) =>
    RustLib.instance.api
        .crateApiInitDatabase(dbPath: dbPath, rawKeyHex: rawKeyHex);

/// Guarda la propuesta confirmada. `db_path` = archivo SQLite en la app.
Future<String> confirmMovement(
        {required String dbPath,
        required String tipo,
        required double monto,
        required String moneda,
        required String categoria,
        required String descripcion,
        required String fecha,
        required String frase}) =>
    RustLib.instance.api.crateApiConfirmMovement(
        dbPath: dbPath,
        tipo: tipo,
        monto: monto,
        moneda: moneda,
        categoria: categoria,
        descripcion: descripcion,
        fecha: fecha,
        frase: frase);

/// Genera una nueva Master Key aleatoria y la envuelve con 12 palabras BIP-39.
Future<VaultInitDto> createVault({String? customPassphrase}) =>
    RustLib.instance.api
        .crateApiCreateVault(customPassphrase: customPassphrase);

/// Desenvuelve la Master Key a partir del payload y la frase de recuperación.
Future<String> recoverMasterKey(
        {required String wrappedRecoveryPayload,
        required String recoveryPhrase}) =>
    RustLib.instance.api.crateApiRecoverMasterKey(
        wrappedRecoveryPayload: wrappedRecoveryPayload,
        recoveryPhrase: recoveryPhrase);

/// Últimos movimientos para la lista.
Future<List<MovementDto>> listMovements(
        {required String dbPath, required PlatformInt64 limit}) =>
    RustLib.instance.api.crateApiListMovements(dbPath: dbPath, limit: limit);

/// Movimiento guardado, listo para la lista de la UI.
class MovementDto {
  final String id;
  final String tipo;
  final double monto;
  final String moneda;
  final String categoria;
  final String descripcion;
  final String fecha;

  const MovementDto({
    required this.id,
    required this.tipo,
    required this.monto,
    required this.moneda,
    required this.categoria,
    required this.descripcion,
    required this.fecha,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      tipo.hashCode ^
      monto.hashCode ^
      moneda.hashCode ^
      categoria.hashCode ^
      descripcion.hashCode ^
      fecha.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MovementDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          tipo == other.tipo &&
          monto == other.monto &&
          moneda == other.moneda &&
          categoria == other.categoria &&
          descripcion == other.descripcion &&
          fecha == other.fecha;
}

/// Lo que Flutter muestra en la tarjeta de confirmación.
class ProposalDto {
  final String tipo;
  final double monto;
  final String categoria;
  final String moneda;
  final String fecha;
  final bool grounded;

  const ProposalDto({
    required this.tipo,
    required this.monto,
    required this.categoria,
    required this.moneda,
    required this.fecha,
    required this.grounded,
  });

  @override
  int get hashCode =>
      tipo.hashCode ^
      monto.hashCode ^
      categoria.hashCode ^
      moneda.hashCode ^
      fecha.hashCode ^
      grounded.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProposalDto &&
          runtimeType == other.runtimeType &&
          tipo == other.tipo &&
          monto == other.monto &&
          categoria == other.categoria &&
          moneda == other.moneda &&
          fecha == other.fecha &&
          grounded == other.grounded;
}

/// DTO con los datos de creación inicial del vault.
class VaultInitDto {
  final String rawMasterKeyHex;
  final String recoveryPhrase;
  final String wrappedRecoveryPayload;

  const VaultInitDto({
    required this.rawMasterKeyHex,
    required this.recoveryPhrase,
    required this.wrappedRecoveryPayload,
  });

  @override
  int get hashCode =>
      rawMasterKeyHex.hashCode ^
      recoveryPhrase.hashCode ^
      wrappedRecoveryPayload.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VaultInitDto &&
          runtimeType == other.runtimeType &&
          rawMasterKeyHex == other.rawMasterKeyHex &&
          recoveryPhrase == other.recoveryPhrase &&
          wrappedRecoveryPayload == other.wrappedRecoveryPayload;
}
