// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AccountDto dco_decode_account_dto(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  ExchangeRateDto dco_decode_box_autoadd_exchange_rate_dto(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw);

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw);

  @protected
  CardStatementDto dco_decode_card_statement_dto(dynamic raw);

  @protected
  CardStatementItemDto dco_decode_card_statement_item_dto(dynamic raw);

  @protected
  CashflowItemDto dco_decode_cashflow_item_dto(dynamic raw);

  @protected
  CategoryReportDto dco_decode_category_report_dto(dynamic raw);

  @protected
  CategorySpendingDto dco_decode_category_spending_dto(dynamic raw);

  @protected
  ExchangeRateDto dco_decode_exchange_rate_dto(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  FinancialKpisDto dco_decode_financial_kpis_dto(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  InstallmentProjectionDto dco_decode_installment_projection_dto(dynamic raw);

  @protected
  List<AccountDto> dco_decode_list_account_dto(dynamic raw);

  @protected
  List<CardStatementItemDto> dco_decode_list_card_statement_item_dto(
      dynamic raw);

  @protected
  List<CashflowItemDto> dco_decode_list_cashflow_item_dto(dynamic raw);

  @protected
  List<CategorySpendingDto> dco_decode_list_category_spending_dto(dynamic raw);

  @protected
  List<ExchangeRateDto> dco_decode_list_exchange_rate_dto(dynamic raw);

  @protected
  List<InstallmentProjectionDto> dco_decode_list_installment_projection_dto(
      dynamic raw);

  @protected
  List<MovementDto> dco_decode_list_movement_dto(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<RecurringRuleDto> dco_decode_list_recurring_rule_dto(dynamic raw);

  @protected
  MovementDto dco_decode_movement_dto(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  ExchangeRateDto? dco_decode_opt_box_autoadd_exchange_rate_dto(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw);

  @protected
  ProposalDto dco_decode_proposal_dto(dynamic raw);

  @protected
  RecurringRuleDto dco_decode_recurring_rule_dto(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  VaultInitDto dco_decode_vault_init_dto(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AccountDto sse_decode_account_dto(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  ExchangeRateDto sse_decode_box_autoadd_exchange_rate_dto(
      SseDeserializer deserializer);

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  CardStatementDto sse_decode_card_statement_dto(SseDeserializer deserializer);

  @protected
  CardStatementItemDto sse_decode_card_statement_item_dto(
      SseDeserializer deserializer);

  @protected
  CashflowItemDto sse_decode_cashflow_item_dto(SseDeserializer deserializer);

  @protected
  CategoryReportDto sse_decode_category_report_dto(
      SseDeserializer deserializer);

  @protected
  CategorySpendingDto sse_decode_category_spending_dto(
      SseDeserializer deserializer);

  @protected
  ExchangeRateDto sse_decode_exchange_rate_dto(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  FinancialKpisDto sse_decode_financial_kpis_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  InstallmentProjectionDto sse_decode_installment_projection_dto(
      SseDeserializer deserializer);

  @protected
  List<AccountDto> sse_decode_list_account_dto(SseDeserializer deserializer);

  @protected
  List<CardStatementItemDto> sse_decode_list_card_statement_item_dto(
      SseDeserializer deserializer);

  @protected
  List<CashflowItemDto> sse_decode_list_cashflow_item_dto(
      SseDeserializer deserializer);

  @protected
  List<CategorySpendingDto> sse_decode_list_category_spending_dto(
      SseDeserializer deserializer);

  @protected
  List<ExchangeRateDto> sse_decode_list_exchange_rate_dto(
      SseDeserializer deserializer);

  @protected
  List<InstallmentProjectionDto> sse_decode_list_installment_projection_dto(
      SseDeserializer deserializer);

  @protected
  List<MovementDto> sse_decode_list_movement_dto(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<RecurringRuleDto> sse_decode_list_recurring_rule_dto(
      SseDeserializer deserializer);

  @protected
  MovementDto sse_decode_movement_dto(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  ExchangeRateDto? sse_decode_opt_box_autoadd_exchange_rate_dto(
      SseDeserializer deserializer);

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  ProposalDto sse_decode_proposal_dto(SseDeserializer deserializer);

  @protected
  RecurringRuleDto sse_decode_recurring_rule_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  VaultInitDto sse_decode_vault_init_dto(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_account_dto(AccountDto self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_exchange_rate_dto(
      ExchangeRateDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_card_statement_dto(
      CardStatementDto self, SseSerializer serializer);

  @protected
  void sse_encode_card_statement_item_dto(
      CardStatementItemDto self, SseSerializer serializer);

  @protected
  void sse_encode_cashflow_item_dto(
      CashflowItemDto self, SseSerializer serializer);

  @protected
  void sse_encode_category_report_dto(
      CategoryReportDto self, SseSerializer serializer);

  @protected
  void sse_encode_category_spending_dto(
      CategorySpendingDto self, SseSerializer serializer);

  @protected
  void sse_encode_exchange_rate_dto(
      ExchangeRateDto self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_financial_kpis_dto(
      FinancialKpisDto self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_installment_projection_dto(
      InstallmentProjectionDto self, SseSerializer serializer);

  @protected
  void sse_encode_list_account_dto(
      List<AccountDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_card_statement_item_dto(
      List<CardStatementItemDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_cashflow_item_dto(
      List<CashflowItemDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_category_spending_dto(
      List<CategorySpendingDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_exchange_rate_dto(
      List<ExchangeRateDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_installment_projection_dto(
      List<InstallmentProjectionDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_movement_dto(
      List<MovementDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_list_recurring_rule_dto(
      List<RecurringRuleDto> self, SseSerializer serializer);

  @protected
  void sse_encode_movement_dto(MovementDto self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_exchange_rate_dto(
      ExchangeRateDto? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_proposal_dto(ProposalDto self, SseSerializer serializer);

  @protected
  void sse_encode_recurring_rule_dto(
      RecurringRuleDto self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_vault_init_dto(VaultInitDto self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
