// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => 1038825605;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'moneyneedle_core',
    ioDirectory: '../core/target/release/',
    webPrefix: 'pkg/',
    wasmBindgenName: 'wasm_bindgen',
  );
}

abstract class RustLibApi extends BaseApi {
  Future<String> crateApiConfirmMovement(
      {required String dbPath,
      required String tipo,
      required double monto,
      required String moneda,
      required String categoria,
      required String descripcion,
      required String fecha,
      required String frase});

  Future<VaultInitDto> crateApiCreateVault({String? customPassphrase});

  Future<bool> crateApiInitDatabase(
      {required String dbPath, String? rawKeyHex});

  Future<List<MovementDto>> crateApiListMovements(
      {required String dbPath, required PlatformInt64 limit});

  Future<ProposalDto> crateApiProposeMocked(
      {required String query, required String fechaHoy});

  Future<ProposalDto> crateApiProposeReal(
      {required String query,
      required String fechaHoy,
      required String cactPath});

  Future<String> crateApiRecoverMasterKey(
      {required String wrappedRecoveryPayload, required String recoveryPhrase});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<String> crateApiConfirmMovement(
      {required String dbPath,
      required String tipo,
      required double monto,
      required String moneda,
      required String categoria,
      required String descripcion,
      required String fecha,
      required String frase}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dbPath, serializer);
        sse_encode_String(tipo, serializer);
        sse_encode_f_64(monto, serializer);
        sse_encode_String(moneda, serializer);
        sse_encode_String(categoria, serializer);
        sse_encode_String(descripcion, serializer);
        sse_encode_String(fecha, serializer);
        sse_encode_String(frase, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 1, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiConfirmMovementConstMeta,
      argValues: [
        dbPath,
        tipo,
        monto,
        moneda,
        categoria,
        descripcion,
        fecha,
        frase
      ],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiConfirmMovementConstMeta => const TaskConstMeta(
        debugName: "confirm_movement",
        argNames: [
          "dbPath",
          "tipo",
          "monto",
          "moneda",
          "categoria",
          "descripcion",
          "fecha",
          "frase"
        ],
      );

  @override
  Future<VaultInitDto> crateApiCreateVault({String? customPassphrase}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_opt_String(customPassphrase, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 2, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_vault_init_dto,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiCreateVaultConstMeta,
      argValues: [customPassphrase],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCreateVaultConstMeta => const TaskConstMeta(
        debugName: "create_vault",
        argNames: ["customPassphrase"],
      );

  @override
  Future<bool> crateApiInitDatabase(
      {required String dbPath, String? rawKeyHex}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dbPath, serializer);
        sse_encode_opt_String(rawKeyHex, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 3, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiInitDatabaseConstMeta,
      argValues: [dbPath, rawKeyHex],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiInitDatabaseConstMeta => const TaskConstMeta(
        debugName: "init_database",
        argNames: ["dbPath", "rawKeyHex"],
      );

  @override
  Future<List<MovementDto>> crateApiListMovements(
      {required String dbPath, required PlatformInt64 limit}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dbPath, serializer);
        sse_encode_i_64(limit, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 4, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_movement_dto,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiListMovementsConstMeta,
      argValues: [dbPath, limit],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiListMovementsConstMeta => const TaskConstMeta(
        debugName: "list_movements",
        argNames: ["dbPath", "limit"],
      );

  @override
  Future<ProposalDto> crateApiProposeMocked(
      {required String query, required String fechaHoy}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(query, serializer);
        sse_encode_String(fechaHoy, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 5, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_proposal_dto,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiProposeMockedConstMeta,
      argValues: [query, fechaHoy],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiProposeMockedConstMeta => const TaskConstMeta(
        debugName: "propose_mocked",
        argNames: ["query", "fechaHoy"],
      );

  @override
  Future<ProposalDto> crateApiProposeReal(
      {required String query,
      required String fechaHoy,
      required String cactPath}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(query, serializer);
        sse_encode_String(fechaHoy, serializer);
        sse_encode_String(cactPath, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 6, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_proposal_dto,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiProposeRealConstMeta,
      argValues: [query, fechaHoy, cactPath],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiProposeRealConstMeta => const TaskConstMeta(
        debugName: "propose_real",
        argNames: ["query", "fechaHoy", "cactPath"],
      );

  @override
  Future<String> crateApiRecoverMasterKey(
      {required String wrappedRecoveryPayload,
      required String recoveryPhrase}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(wrappedRecoveryPayload, serializer);
        sse_encode_String(recoveryPhrase, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 7, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiRecoverMasterKeyConstMeta,
      argValues: [wrappedRecoveryPayload, recoveryPhrase],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiRecoverMasterKeyConstMeta => const TaskConstMeta(
        debugName: "recover_master_key",
        argNames: ["wrappedRecoveryPayload", "recoveryPhrase"],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<MovementDto> dco_decode_list_movement_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_movement_dto).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  MovementDto dco_decode_movement_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return MovementDto(
      id: dco_decode_String(arr[0]),
      tipo: dco_decode_String(arr[1]),
      monto: dco_decode_f_64(arr[2]),
      moneda: dco_decode_String(arr[3]),
      categoria: dco_decode_String(arr[4]),
      descripcion: dco_decode_String(arr[5]),
      fecha: dco_decode_String(arr[6]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  ProposalDto dco_decode_proposal_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return ProposalDto(
      tipo: dco_decode_String(arr[0]),
      monto: dco_decode_f_64(arr[1]),
      categoria: dco_decode_String(arr[2]),
      moneda: dco_decode_String(arr[3]),
      fecha: dco_decode_String(arr[4]),
      grounded: dco_decode_bool(arr[5]),
    );
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  VaultInitDto dco_decode_vault_init_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return VaultInitDto(
      rawMasterKeyHex: dco_decode_String(arr[0]),
      recoveryPhrase: dco_decode_String(arr[1]),
      wrappedRecoveryPayload: dco_decode_String(arr[2]),
    );
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<MovementDto> sse_decode_list_movement_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <MovementDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_movement_dto(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  MovementDto sse_decode_movement_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_tipo = sse_decode_String(deserializer);
    var var_monto = sse_decode_f_64(deserializer);
    var var_moneda = sse_decode_String(deserializer);
    var var_categoria = sse_decode_String(deserializer);
    var var_descripcion = sse_decode_String(deserializer);
    var var_fecha = sse_decode_String(deserializer);
    return MovementDto(
        id: var_id,
        tipo: var_tipo,
        monto: var_monto,
        moneda: var_moneda,
        categoria: var_categoria,
        descripcion: var_descripcion,
        fecha: var_fecha);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ProposalDto sse_decode_proposal_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_tipo = sse_decode_String(deserializer);
    var var_monto = sse_decode_f_64(deserializer);
    var var_categoria = sse_decode_String(deserializer);
    var var_moneda = sse_decode_String(deserializer);
    var var_fecha = sse_decode_String(deserializer);
    var var_grounded = sse_decode_bool(deserializer);
    return ProposalDto(
        tipo: var_tipo,
        monto: var_monto,
        categoria: var_categoria,
        moneda: var_moneda,
        fecha: var_fecha,
        grounded: var_grounded);
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  VaultInitDto sse_decode_vault_init_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_rawMasterKeyHex = sse_decode_String(deserializer);
    var var_recoveryPhrase = sse_decode_String(deserializer);
    var var_wrappedRecoveryPayload = sse_decode_String(deserializer);
    return VaultInitDto(
        rawMasterKeyHex: var_rawMasterKeyHex,
        recoveryPhrase: var_recoveryPhrase,
        wrappedRecoveryPayload: var_wrappedRecoveryPayload);
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_movement_dto(
      List<MovementDto> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_movement_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_movement_dto(MovementDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.tipo, serializer);
    sse_encode_f_64(self.monto, serializer);
    sse_encode_String(self.moneda, serializer);
    sse_encode_String(self.categoria, serializer);
    sse_encode_String(self.descripcion, serializer);
    sse_encode_String(self.fecha, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_proposal_dto(ProposalDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.tipo, serializer);
    sse_encode_f_64(self.monto, serializer);
    sse_encode_String(self.categoria, serializer);
    sse_encode_String(self.moneda, serializer);
    sse_encode_String(self.fecha, serializer);
    sse_encode_bool(self.grounded, serializer);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_vault_init_dto(VaultInitDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.rawMasterKeyHex, serializer);
    sse_encode_String(self.recoveryPhrase, serializer);
    sse_encode_String(self.wrappedRecoveryPayload, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
